export { LoginPage } from './login/page'
export { DashboardPage } from './dashboard/page'
export { PatientsPage } from './patients/page'
export { PatientPreregisterPage } from './patients/preregister/page'
export { SettingsPage } from './settings/page'
